### ISSUE TITLE
Can you supply the training dataset?

### ISSUE THREAD

**Issue by HongYu-speech** [vvirgooo2/Uyghur-Translator#1]
Thank you for your model, can you tell me where download the training dataset?

**Comment by atie-m2g** [comment]
> Thank you for your model, can you tell me where download the training dataset?

Hi, bro. Maybe I know where it is, but I'm NOT so sure that this is you really wanted ones
https://gitee.com/hf-models/nllb-200-distilled-600M.git

**Comment by vvirgooo2** [comment]
> Thank you for your model, can you tell me where download the training dataset?

Hi, we have not trained the model, we just use the model from MMS. You can find everything in [https://huggingface.co/facebook/mms-1b-all](url) and [https://github.com/facebookresearch/fairseq/tree/main/examples/mms#asr](url).

**Comment by vvirgooo2** [comment]
I have updated the README for more information.
